stages:
  - deploy

deploy:
  image: ruby:2.4
  stage: deploy
  before_script:
    - pip install -r requirements.txt
    - python manage.py makemigrations
    - python manage.py migrate
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - dpl --provider=heroku --app=$HEROKU_APPNAME --api-key=$HEROKU_APIKEY 
  environment:
    name: development
    url: $HEROKU_APP_HOST
  only:
    - master